
database: $DATAVAULT_DATABASE_URI
linktab: ref_linkage
report: Linkage Report.xlsx

skip:
  - ['occrp.poi', 'on.sanctions']

views:

  # Moldova
  md.corp.founder:
    label: "Moldova Company Founders"
    tables:
      - md_company
      - md_company_founder
    joins:
      - left: md_company.company_id
        right: md_company_founder.company_id
    key: md_company_founder.name
    fields:
      - column: md_company.name
        label: Company Name
      - column: md_company.idno_cod_fiscal
        label: Tax ID
      - column: md_company_founder.name
        label: Founder Name
  md.tender.blacklist:
    label: "Moldova Procurement Blacklist"
    tables:
      - md_blacklist
    key: md_blacklist.name
    fields:
      - column: md_blacklist.name
        label: Name
  md.party.donation:
    label: "Moldova Party Donations"
    tables:
      - md_party_donation
      - md_party_filing
    joins:
      - left: md_party_donation.filename
        right: md_party_filing.filepath
    key: md_party_donation.employer
    fields:
      - column: md_party_filing.party
        label: Party
      - column: md_party_donation.name
        label: Donor
      - column: md_party_donation.employer
        label: Employer
      - column: md_party_donation.amount_num
        label: Amount

  # Persons of Interest
  occrp.poi:
    label: "OCCRP Persons of Interest"
    tables:
      - pep_spindle
    key: pep_spindle.name
    fields:
      - column: pep_spindle.name
        label: Name
      - column: pep_spindle.collection
        label: Watchlist
      - column: pep_spindle.summary
        label: Summary
  on.sanctions:
    label: "International Sanctions and PEPs"
    tables:
      - pep_entity
      - pep_xref
    joins:
      - left: pep_entity.uid
        right: pep_xref.uid
    key: pep_xref.alias
    fields:
      - column: pep_entity.name
        label: Canonical Name
      - column: pep_entity.source_id
        label: Source
      - column: pep_entity.publisher
        label: Publisher
      - column: pep_entity.summary
        label: Summary
      - column: pep_entity.type
        label: Type
